// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// School is the predicate function for school builders.
type School func(*sql.Selector)

// Student is the predicate function for student builders.
type Student func(*sql.Selector)
